#ifndef TRIANGLE_VERSION_H
#define TRIANGLE_VERSION_H

#define TRIANGLE_VERSION_MAJOR 1
#define TRIANGLE_VERSION_MINOR 6
#define TRIANGLE_VERSION_PATCH 0

#define TRIANGLE_VERSION "1.6.0"

#endif /* TRIANGLE_VERSION_H */
